live_config_reload = true
working_directory = "None"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.bold]
family = "Roboto Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
key = "Key1"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==1' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==2' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==3' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==4' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==5' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==6' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==7' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==8' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | awk 'NR==9' | awk -F: '{print $1}'); tmux switch -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "T"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "tmux switch -t `tmux new -dP`"]
program = "zsh"

[[keyboard.bindings]]
key = "W"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "id=$(tmux list-sessions | grep '(attached)' | awk -F: '{print $1}'); tmux switchc -p; tmux kill-session -t $id"]
program = "zsh"

[[keyboard.bindings]]
key = "Left"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "tmux switch -p"]
program = "zsh"

[[keyboard.bindings]]
key = "Right"
mods = "Command"

[keyboard.bindings.command]
args = ["-l", "-c", "tmux switch -n"]
program = "zsh"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "source ~/.zshrc; tmux attach 2> /dev/null || tmux"]
program = "zsh"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 4
y = 4
