import = [
  "~/.config/alacritty/colors.toml"
]

live_config_reload = true
working_directory = "None"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 12.0

[font.bold]
family = "Roboto Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

# Only keep Alacritty-specific bindings
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

# [[keyboard.bindings]]
# action = "ClearHistory"
# key = "K"
# mods = "Command"

# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mods = "Command"
#
# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

# [[keyboard.bindings]]
# action = "CreateNewWindow"
# key = "N"
# mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "source ~/.zshrc; zellij -c ~/.dotfiles/zellij/config.kdl attach --create default"]
# args = ["-l", "-c", "source ~/.zshrc; zellij"]
program = "zsh"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 4
y = 4
