shell = "zsh -c '{}'"
default-scheme = "base16-eighties"
# hooks = ["tmux source-file ~/.tmux.conf"]
# hooks = ["zellij kill-session default && sleep 1 && open -a Alacritty"]
# hooks = ["pkill alacritty && open -a Alacritty"]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-alacritty"
themes-dir = "themes/alacritty"
hook = "cp -f %f ~/.config/alacritty/colors.toml"

[[items]]
path = "~/.dotfiles/tinty/custom-zellij-template"
name = "custom-zellij"
themes-dir = "colors"
hook = "cp -f %f ~/.config/zellij/themes/base16.kdl && touch ~/.dotfiles/zellij/config.kdl"

[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
themes-dir = "colors"
hook = "cp -f %f ~/.config/tmux/colors.conf"

[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
hook = "cp -f %f ~/.base16_theme"

[[items]]
path = "https://github.com/tinted-theming/base16-vim"
name = "tinted-vim"
themes-dir = "colors"
hook = "cp -f %f ~/.config/nvim/theme.vim"
