# Setup the environment (needs to be on top)
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh
export PROJECTS=$HOME/code

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
source ~/.localrc

# Tmux colorschemes
export TERM="xterm-256color"

# Setup paths
source $ZSH/exports.zsh

# Functions to import
fpath=($ZSH/functions $fpath)
autoload -U $ZSH/functions/c(:t)
autoload -U $ZSH/functions/smartextract(:t)

# Import additional .zsh files
source $ZSH/aliases.zsh
source $ZSH/config.zsh
source $ZSH/prompt.zsh
source $ZSH/plugins.zsh # Slow thanks to base16

source $ZSH/plugins/fzf.zsh

# Remove PATH duplicates
typeset -U path cdpath manpath fpath

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit;
else
	compinit -C;
fi;

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

