# Setup the environment (needs to be on top)
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh
export PROJECTS=$HOME/code

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
source ~/.localrc

# Tmux colorschemes
export TERM="xterm-256color"

# Setup the theme
[ -f $ZSH/theme.zsh ] && source $ZSH/theme.zsh

# Setup paths
source $ZSH/exports.zsh

# Functions to import
fpath=($ZSH/functions $fpath)
autoload -U $ZSH/functions/c(:t)
autoload -U $ZSH/functions/smartextract(:t)

# Import additional .zsh files
source $ZSH/aliases.zsh
source $ZSH/config.zsh
source $ZSH/prompt.zsh
source $ZSH/plugins.zsh # Slow thanks to base16

source $ZSH/plugins/fzf.zsh

# Remove PATH duplicates
typeset -U path cdpath manpath fpath

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit;
else
	compinit -C;
fi;

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

fpath+=${ZDOTDIR:-~}/.zsh_functions

# Created by `pipx` on 2023-12-14 16:21:51
export PATH="$PATH:/Users/pulleasy/.local/bin"
